spring.application.name=biblioteca-api
server.port=8081

# H2
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# Garante que a inicialização do DB ocorre aós a config do datasource
spring.jpa.defer-datasource-initialization=true
# Garante execuções dos cripts de inicialização sejam
# executandp no mesmo banco de dado em memória.
spring.sql.init.mode=always

# Habilita a exibiçaõ de consultas no console
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

